[tool.poetry]
name = "pgtest"
version = "0.1.0"
description = ""
authors = ["Toke Friis <tokefriis@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
psycopg2 = "^2.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
